[package]
name = "plaintext"
version = "3.0.0"
authors = ["ElementalAlchemist <ElementAlchemist7@gmail.com>"]
edition = "2018"

[dependencies]
robobo = { path = "../.." }

[lib]
crate-type = ["dylib"]