[package]
name = "plaintext"
version = "3.0.0"
authors = ["ElementalAlchemist <ElementAlchemist7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
robobo = { path = "../.." }

[lib]
crate-type = ["dylib"]